### ISSUE TITLE
[BUG] Fork

### ISSUE THREAD

**Issue by bdronneau** [ViBiOh/ketchup#43]
## Description
Can not add fork

## Step to reproduce
- Create
  - Name: MeilleursAgents/ma.traefik
  - Version: 1.0.0

**Comment by ViBiOh** [comment]
Although we see some releases here https://github.com/MeilleursAgents/ma.traefik/releases, they are unreachable fro the Github API v3, if they don't have text.

**Comment by bdronneau** [comment]
Can you parse tags ? https://developer.github.com/v3/repos/#list-tags ?

**Comment by ViBiOh** [comment]
I can parse tag in case of no release found. There is no date in the returned payload, so ordering by name descending should return me the "latest" I think. I'll try

**Comment by ViBiOh** [comment]
I've contacted Github support for question about this, if this is an expected behavior and how to get latest release in a deterministic manner when there are no "releases" but only tags.

**Comment by ViBiOh** [comment]
Solved in v1.2.0
