### ISSUE TITLE
[BUG] Add ghcr registry  source

### ISSUE THREAD

**Issue by bdronneau** [ViBiOh/ketchup#498]
**Describe the bug**

When I add a github registry I've got

```
get releases for `ghcr.io/siderolabs/installer`: fetch tags: HTTP/403 Date: Thu, 05 Oct 2023 13:09:32 GMT Content-Length: 57 Content-Type: text/plain; charset=utf-8 X-Github-Request-Id: 83C5:C786:F96873:FF3E44:651EB58C {"errors":[{"code":"DENIED","message":"invalid token"}]} not found
```

**Steps to Reproduce**
1. Go to https://ketchup.vibioh.fr/app/#create-modal
2. Fill with ghcr.io/siderolabs/installer / stable / 1.5.3 / daily
3. Click on create
5. See error

**Environment**
Google chrome `117.0.5938.132 (Official Build) (arm64)`

**Expected behavior**
Get versions from this registry

**Screenshots**

N/A

**Additional context**

akwakwak

**Comment by ViBiOh** [comment]
Hi @bdronneau,

Thanks for the submission. I had identified this issue before and I didn't addressed it yet. In fact, I'd need to provide a personnal access token to talk to GitHub, which will consume my own quota. I'll search for alternatives and if not put mine in order to unblock you.
