### ISSUE TITLE
[FEAT] pre-release version

### ISSUE THREAD

**Issue by bdronneau** [ViBiOh/ketchup#89]
**Describe the feature**
Hey,

Thank for this awesome tool.
I'm using [consul](https://github.com/hashicorp/consul) and in release they have a "pre-release".

Can you seperate those versions ? Like two lines ?

Best

**Screenshots**
![Screenshot 2020-05-20 at 9 27 06 AM](https://user-images.githubusercontent.com/4170158/82417623-1b212280-9a7c-11ea-885c-59ca45e45ba0.png)

**Comment by ViBiOh** [comment]
Hi @bdronneau 

Thank you for you interest in this tool.

I've made changed to detect and ignore `beta` or `rc` version, so I think I'm capable to deal with it. It will be grouped with the "semver" functionality #29
